# Use postgres/example user/password credentials
version: "3.1"

services:
  hydra:
    container_name: hydra
    image: oryd/hydra:v2.0.3
    ports:
      - "4444:4444" # Public port
      - "4445:4445" # Admin port
      - "5555:5555" # Port for hydra token user
    command: serve -c /etc/config/hydra/hydra.yml all --dev
    volumes:
      - type: bind
        source: ./packages/config/hydra/prod
        target: /etc/config/hydra
    environment:
      - DSN=${HYDRA_DATABASE_URL}
      - OIDC_SUBJECT_IDENTIFIERS_PAIRWISE_SALT=${OIDC_SUBJECT_IDENTIFIERS_PAIRWISE_SALT}
      - SECRETS_SYSTEM=${SECRETS_SYSTEM}
      - URLS_SELF_ISSUER=${URLS_SELF_ISSUER}
    restart: unless-stopped
    depends_on:
      - hydra-migrate
    networks:
      - intranet
  hydra-migrate:
    image: oryd/hydra:v2.0.3
    environment:
      - DSN=${HYDRA_DATABASE_URL}
      - OIDC_SUBJECT_IDENTIFIERS_PAIRWISE_SALT=${OIDC_SUBJECT_IDENTIFIERS_PAIRWISE_SALT}
      - SECRETS_SYSTEM=${SECRETS_SYSTEM}
      - URLS_SELF_ISSUER=${URLS_SELF_ISSUER}
    command: migrate -c /etc/config/hydra/hydra.yml sql -e --yes
    volumes:
      - type: bind
        source: ./packages/config/hydra/prod
        target: /etc/config/hydra
    restart: on-failure
    networks:
      - intranet

networks:
  intranet:
